### ISSUE TITLE
Persistent Binderhub import link

### ISSUE THREAD

**Issue by arnim** [chipmuenk/dsp_fpga#3]
Die Materialien können auch direkt dauerhaft mit einem Link in den Persistent Binderhub / GESIS Notebooks importiert werden.

### Beispiel:

Standard mybinder.org
> http://mybinder.org/v2/gh/binder-examples/requirements/master

GESIS Notebooks Persistent Binder
> http://notebooks.gesis.org/services/binder/v2/gh/binder-examples/requirements/master

Für DSP 
> http://notebooks.gesis.org/services/binder/v2/gh/chipmuenk/dsp/master

Importiert ein User ein bereits bestehendes Projekt erneuert werden nur die Dependencies (requirements.txt) aktualisiert.

**Comment by chipmuenk** [comment]
Vielen Dank für die Infos! Ich bin nur nicht so fit mit Binder etc ... was ist die Vorgehensweise und was sind die Vorteile? Ich (bzw. Studenten von mir) legen einen Gesis Account an und können dann über den Link direkt in einer fertig konfigurierten Jupyter Umgebung mit dem ausgewählten Repo loslegen? Das hört sich sehr komfortabel an!

**Comment by arnim** [comment]
> Ich (bzw. Studenten von mir) legen einen Gesis Account an und können dann über den Link direkt in einer fertig konfigurierten Jupyter Umgebung mit dem ausgewählten Repo loslegen?

Ja und für den Fall, dass noch kein Account besteht, werden die Studenten als Teil des Prozesses aufgefordert einen Account zu erstellen. Wir haben den Prozess für u.A. [GESIS Trainings](https://training.gesis.org/) entwickelt hoffen aber das Angebot über die SozWiss hinaus [zugänglich zu machen](https://cfp.jupytercon.com/2020/schedule/presentation/193/a-persistent-binderhub-democratizing-access-to-computational-resources-in-the-social-sciences/).

Da wir uns mit der Infrastruktur aber noch in der Aufbausphase befinden würde ich noch empfehlen, dass regelmäßige Backups gemacht werden.
