### ISSUE TITLE
README: Notebook Links 404

### ISSUE THREAD

**Issue by dasteihn** [chipmuenk/dsp_fpga#4]
Hi Prof.
die Notebooks 7-11 im README führen auf 404.

**Comment by chipmuenk** [comment]
Ich hatte nicht damit gerechnet, dass auch Menschen außerhalb meiner Kurse mit den Notebooks arbeiten :-) Danke für die Erinnerung, ich werde über die nächsten Wochen die Notebooks aktualisieren.
